const elitePlayers = [
  { "name": "Axar Patel", "role": "all-rounder", "level": "elite", "score": 94, "overseas": false },
  { "name": "Kuldeep Yadav", "role": "bowler", "level": "elite", "score": 93, "overseas": false },
  { "name": "Harry Brook", "role": "batter", "level": "elite", "score": 92, "overseas": true },
  { "name": "T Natarajan", "role": "bowler", "level": "elite", "score": 91, "overseas": false },
  { "name": "Faf du Plessis", "role": "batter", "level": "elite", "score": 90, "overseas": true },
  { "name": "Rajat Patidar", "role": "batter", "level": "elite", "score": 90, "overseas": false },
  { "name": "Liam Livingstone", "role": "all-rounder", "level": "elite", "score": 92, "overseas": true },
  { "name": "Phil Salt", "role": "wicket-keeper batter", "level": "elite", "score": 91, "overseas": true },
  { "name": "Josh Hazlewood", "role": "bowler", "level": "elite", "score": 93, "overseas": true },
  { "name": "Bhuvneshwar Kumar", "role": "bowler", "level": "elite", "score": 92, "overseas": false },
  { "name": "Krunal Pandya", "role": "all-rounder", "level": "elite", "score": 90, "overseas": false },
  { "name": "Tim David", "role": "all-rounder", "level": "elite", "score": 89, "overseas": true },
  { "name": "Ruturaj Gaikwad", "role": "batter", "level": "elite", "score": 93, "overseas": false },
  { "name": "Ravindra Jadeja", "role": "all-rounder", "level": "elite", "score": 94, "overseas": false },
  { "name": "Noor Ahmad", "role": "bowler", "level": "elite", "score": 92, "overseas": true },
  { "name": "R Ashwin", "role": "bowler", "level": "elite", "score": 94, "overseas": false },
  { "name": "Devon Conway", "role": "batter", "level": "elite", "score": 91, "overseas": true },
  { "name": "Sam Curran", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Tilak Varma", "role": "all-rounder", "level": "elite", "score": 90, "overseas": false },
  { "name": "Trent Boult", "role": "bowler", "level": "elite", "score": 92, "overseas": true },
  { "name": "Deepak Chahar", "role": "bowler", "level": "elite", "score": 90, "overseas": false },
  { "name": "Will Jacks", "role": "all-rounder", "level": "elite", "score": 88, "overseas": true },
  { "name": "Mitchell Santner", "role": "all-rounder", "level": "elite", "score": 85, "overseas": true },
  { "name": "Jonny Bairstow", "role": "wicket-keeper batter", "level": "elite", "score": 89, "overseas": true },
  { "name": "Charith Asalanka", "role": "batter", "level": "elite", "score": 88, "overseas": true },
  { "name": "Arshdeep Singh", "role": "bowler", "level": "elite", "score": 95, "overseas": false },
  { "name": "Shreyas Iyer", "role": "batter", "level": "elite", "score": 98, "overseas": false },
  { "name": "Yuzvendra Chahal", "role": "bowler", "level": "elite", "score": 94, "overseas": false },
  { "name": "Marcus Stoinis", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Glenn Maxwell", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Lockie Ferguson", "role": "bowler", "level": "elite", "score": 93, "overseas": true },
  { "name": "Josh Inglis", "role": "wicket-keeper batter", "level": "elite", "score": 90, "overseas": true },
  { "name": "Marco Jansen", "role": "all-rounder", "level": "elite", "score": 92, "overseas": true },
  { "name": "Heinrich Klaasen", "role": "wicket-keeper batter", "level": "elite", "score": 95, "overseas": true },
  { "name": "Abhishek Sharma", "role": "all-rounder", "level": "elite", "score": 93, "overseas": false },
  { "name": "Travis Head", "role": "batter", "level": "elite", "score": 94, "overseas": true },
  { "name": "Mohammed Shami", "role": "bowler", "level": "elite", "score": 92, "overseas": false },
  { "name": "Ishan Kishan", "role": "wicket-keeper batter", "level": "elite", "score": 93, "overseas": false },
  { "name": "Adam Zampa", "role": "bowler", "level": "elite", "score": 87, "overseas": true },
  { "name": "Sai Sudharsan", "role": "batter", "level": "elite", "score": 90, "overseas": false },
  { "name": "Rahul Tewatia", "role": "all-rounder", "level": "elite", "score": 88, "overseas": false },
  { "name": "Mohammed Siraj", "role": "bowler", "level": "elite", "score": 93, "overseas": false },
  { "name": "Kagiso Rabada", "role": "bowler", "level": "elite", "score": 94, "overseas": true },
  { "name": "Glenn Phillips", "role": "all-rounder", "level": "elite", "score": 89, "overseas": true },
  { "name": "Nicholas Pooran", "role": "wicket-keeper batter", "level": "elite", "score": 92, "overseas": true },
  { "name": "Aiden Markram", "role": "batter", "level": "elite", "score": 90, "overseas": true },
  { "name": "David Miller", "role": "batter", "level": "elite", "score": 89, "overseas": true },
  { "name": "Mitchell Marsh", "role": "all-rounder", "level": "elite", "score": 91, "overseas": true },
  { "name": "Rinku Singh", "role": "batter", "level": "elite", "score": 92, "overseas": false },
  { "name": "Varun Chakravarthy", "role": "bowler", "level": "elite", "score": 90, "overseas": false },
  { "name": "Venkatesh Iyer", "role": "all-rounder", "level": "elite", "score": 93, "overseas": false },
  { "name": "Quinton de Kock", "role": "wicket-keeper batter", "level": "elite", "score": 90, "overseas": true },
  { "name": "Anrich Nortje", "role": "bowler", "level": "elite", "score": 92, "overseas": true },
  { "name": "Ajinkya Rahane", "role": "batter", "level": "elite", "score": 88, "overseas": false },
  { "name": "Rovman Powell", "role": "all-rounder", "level": "elite", "score": 89, "overseas": true },
  { "name": "Moeen Ali", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Umran Malik", "role": "bowler", "level": "elite", "score": 89, "overseas": false },
  { "name": "Sanju Samson", "role": "wicket-keeper batter", "level": "elite", "score": 94, "overseas": false },
  { "name": "Yashasvi Jaiswal", "role": "batter", "level": "elite", "score": 93, "overseas": false },
  { "name": "Wanindu Hasaranga", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Maheesh Theekshana", "role": "bowler", "level": "elite", "score": 89, "overseas": true },
  { "name": "Steve Smith", "role": "batter", "level": "elite", "score": 92, "overseas": true },
  { "name": "Mustafizur Rahman", "role": "bowler", "level": "elite", "score": 91, "overseas": true },
  { "name": "Jonny Bairstow", "role": "wicket-keeper", "level": "elite", "score": 90, "overseas": true },
  { "name": "Jason Holder", "role": "all-rounder", "level": "elite", "score": 90, "overseas": true },
  { "name": "Adil Rashid", "role": "bowler", "level": "elite", "score": 90, "overseas": true }
];

const proPlayers = [
  { "name": "Tristan Stubbs", "role": "batter", "level": "pro", "score": 89, "overseas": true },
  { "name": "Abhishek Porel", "role": "wicket-keeper", "level": "pro", "score": 87, "overseas": false },
  { "name": "Jake Fraser-McGurk", "role": "batter", "level": "pro", "score": 88, "overseas": true },
  { "name": "Karun Nair", "role": "batter", "level": "pro", "score": 80, "overseas": false },
  { "name": "Sameer Rizvi", "role": "all-rounder", "level": "pro", "score": 82, "overseas": false },
  { "name": "Ashutosh Sharma", "role": "all-rounder", "level": "pro", "score": 84, "overseas": false },
  { "name": "Mohit Sharma", "role": "bowler", "level": "pro", "score": 82, "overseas": false },
  { "name": "Mukesh Kumar", "role": "bowler", "level": "pro", "score": 85, "overseas": false },
  { "name": "Darshan Nalkande", "role": "all-rounder", "level": "pro", "score": 81, "overseas": false },
  { "name": "Vipraj Nigam", "role": "all-rounder", "level": "pro", "score": 80, "overseas": false },
  { "name": "Dushmantha Chameera", "role": "bowler", "level": "pro", "score": 82, "overseas": true },
  { "name": "Donovan Ferreira", "role": "wicket-keeper", "level": "pro", "score": 81, "overseas": true },
  { "name": "Yash Dayal", "role": "bowler", "level": "pro", "score": 85, "overseas": false },
  { "name": "Jitesh Sharma", "role": "wicket-keeper batter", "level": "pro", "score": 86, "overseas": false },
  { "name": "Rasikh Dar", "role": "bowler", "level": "pro", "score": 84, "overseas": false },
  { "name": "Suyash Sharma", "role": "bowler", "level": "pro", "score": 83, "overseas": false },
  { "name": "Swapnil Singh", "role": "bowler", "level": "pro", "score": 75, "overseas": false },
  { "name": "Romario Shepherd", "role": "all-rounder", "level": "pro", "score": 87, "overseas": true },
  { "name": "Jacob Bethell", "role": "all-rounder", "level": "pro", "score": 88, "overseas": true },
  { "name": "Nuwan Thushara", "role": "bowler", "level": "pro", "score": 85, "overseas": true },
  { "name": "Devdutt Padikkal", "role": "batter", "level": "pro", "score": 88, "overseas": false },
  { "name": "Lungi Ngidi", "role": "bowler", "level": "pro", "score": 85, "overseas": true },
  { "name": "Blessing Muzarabani", "role": "bowler", "level": "pro", "score": 85, "overseas": true },
  { "name": "Shivam Dube", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Matheesha Pathirana", "role": "bowler", "level": "pro", "score": 86, "overseas": true },
  { "name": "Rachin Ravindra", "role": "all-rounder", "level": "pro", "score": 87, "overseas": true },
  { "name": "Rahul Tripathi", "role": "batter", "level": "pro", "score": 86, "overseas": false },
  { "name": "Khaleel Ahmed", "role": "bowler", "level": "pro", "score": 84, "overseas": false },
  { "name": "Vijay Shankar", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Deepak Hooda", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Gurjapneet Singh", "role": "bowler", "level": "pro", "score": 83, "overseas": false },
  { "name": "Nathan Ellis", "role": "bowler", "level": "pro", "score": 82, "overseas": true },
  { "name": "Jamie Overton", "role": "all-rounder", "level": "pro", "score": 84, "overseas": true },
  { "name": "Anshul Kamboj", "role": "all-rounder", "level": "pro", "score": 83, "overseas": false },
  { "name": "Naman Dhir", "role": "wicket-keeper batter", "level": "pro", "score": 80, "overseas": false },
  { "name": "Robin Minz", "role": "wicket-keeper batter", "level": "pro", "score": 78, "overseas": false },
  { "name": "Karan Sharma", "role": "all-rounder", "level": "pro", "score": 75, "overseas": false },
  { "name": "Ryan Rickelton", "role": "wicket-keeper batter", "level": "pro", "score": 82, "overseas": true },
  { "name": "Allah Ghazanfar", "role": "all-rounder", "level": "pro", "score": 80, "overseas": true },
  { "name": "Reece Topley", "role": "bowler", "level": "pro", "score": 80, "overseas": true },
  { "name": "Richard Gleeson", "role": "bowler", "level": "pro", "score": 80, "overseas": true },
  { "name": "Prabhsimran Singh", "role": "wicket-keeper", "level": "pro", "score": 82, "overseas": false },
  { "name": "Shashank Singh", "role": "all-rounder", "level": "pro", "score": 83, "overseas": false },
  { "name": "Nehal Wadhera", "role": "batter", "level": "pro", "score": 85, "overseas": false },
  { "name": "Harpreet Brar", "role": "all-rounder", "level": "pro", "score": 82, "overseas": false },
  { "name": "Vishnu Vinod", "role": "wicket-keeper batter", "level": "pro", "score": 81, "overseas": false },
  { "name": "Vijaykumar Vyshak", "role": "bowler", "level": "pro", "score": 80, "overseas": false },
  { "name": "Yash Thakur", "role": "bowler", "level": "pro", "score": 80, "overseas": false },
  { "name": "Priyansh Arya", "role": "batter", "level": "pro", "score": 87, "overseas": false },
  { "name": "Pyla Avinash", "role": "batter", "level": "pro", "score": 80, "overseas": false },
  { "name": "Suryansh Shedge", "role": "all-rounder", "level": "pro", "score": 82, "overseas": false },
  { "name": "Aaron Hardie", "role": "all-rounder", "level": "pro", "score": 85, "overseas": true },
  { "name": "Azmatullah Omarzai", "role": "all-rounder", "level": "pro", "score": 88, "overseas": true },
  { "name": "Nitish Kumar Reddy", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Harshal Patel", "role": "bowler", "level": "pro", "score": 88, "overseas": false },
  { "name": "Rahul Chahar", "role": "bowler", "level": "pro", "score": 82, "overseas": false },
  { "name": "Abhinav Manohar", "role": "batter", "level": "pro", "score": 88, "overseas": false },
  { "name": "Simarjeet Singh", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Jaidev Unadkat", "role": "bowler", "level": "pro", "score": 83, "overseas": false },
  { "name": "Brydon Carse", "role": "all-rounder", "level": "pro", "score": 84, "overseas": true },
  { "name": "Kamindu Mendis", "role": "all-rounder", "level": "pro", "score": 84, "overseas": true },
  { "name": "Eshan Malinga", "role": "bowler", "level": "pro", "score": 82, "overseas": true },
  { "name": "Shahrukh Khan", "role": "batter", "level": "pro", "score": 85, "overseas": false },
  { "name": "Prasidh Krishna", "role": "bowler", "level": "pro", "score": 88, "overseas": false },
  { "name": "Washington Sundar", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Sherfane Rutherford", "role": "all-rounder", "level": "pro", "score": 84, "overseas": true },
  { "name": "Gerald Coetzee", "role": "bowler", "level": "pro", "score": 83, "overseas": true },
  { "name": "R Sai Kishore", "role": "bowler", "level": "pro", "score": 82, "overseas": false },
  { "name": "Mahipal Lomror", "role": "batter", "level": "pro", "score": 82, "overseas": false },
  { "name": "Ravi Bishnoi", "role": "bowler", "level": "pro", "score": 85, "overseas": false },
  { "name": "Mayank Yadav", "role": "bowler", "level": "pro", "score": 84, "overseas": false },
  { "name": "Mohsin Khan", "role": "all-rounder", "level": "pro", "score": 83, "overseas": false },
  { "name": "Ayush Badoni", "role": "batter", "level": "pro", "score": 83, "overseas": false },
  { "name": "Shardul Thakur", "role": "all-rounder", "level": "pro", "score": 86, "overseas": false },
  { "name": "Harshit Rana", "role": "bowler", "level": "pro", "score": 85, "overseas": false },
  { "name": "Ramandeep Singh", "role": "all-rounder", "level": "pro", "score": 85, "overseas": false },
  { "name": "Rahmanullah Gurbaz", "role": "wicket-keeper batter", "level": "pro", "score": 88, "overseas": true },
  { "name": "Angkrish Raghuvanshi", "role": "batter", "level": "pro", "score": 82, "overseas": false },
  { "name": "Vaibhav Arora", "role": "bowler", "level": "pro", "score": 80, "overseas": false },
  { "name": "Mayank Markande", "role": "bowler", "level": "pro", "score": 78, "overseas": false },
  { "name": "Manish Pandey", "role": "batter", "level": "pro", "score": 85, "overseas": false },
  { "name": "Anukul Roy", "role": "all-rounder", "level": "pro", "score": 80, "overseas": false },
  { "name": "Spencer Johnson", "role": "bowler", "level": "pro", "score": 83, "overseas": true },
  { "name": "Riyan Parag", "role": "all-rounder", "level": "pro", "score": 86, "overseas": false },
  { "name": "Shimron Hetmyer", "role": "batter", "level": "pro", "score": 85, "overseas": true },
  { "name": "Dhruv Jurel", "role": "wicket-keeper batter", "level": "pro", "score": 88, "overseas": false },
  { "name": "Sandeep Sharma", "role": "bowler", "level": "pro", "score": 83, "overseas": false },
  { "name": "Tushar Deshpande", "role": "bowler", "level": "pro", "score": 84, "overseas": false },
  { "name": "Fazalhaq Farooqi", "role": "bowler", "level": "pro", "score": 84, "overseas": true },
  { "name": "Akash Deep", "role": "bowler", "level": "pro", "score": 83, "overseas": false },
  { "name": "Abdul Samad", "role": "all-rounder", "level": "pro", "score": 83, "overseas": false },
  { "name": "Shahbaz Ahmed", "role": "all-rounder", "level": "pro", "score": 82, "overseas": false },
  { "name": "Matthew Breetzke", "role": "batter", "level": "pro", "score": 82, "overseas": true },
  { "name": "Rilee Rossouw", "role": "batter", "level": "pro", "score": 88, "overseas": true },
  { "name": "Kyle Mayers", "role": "all-rounder", "level": "pro", "score": 87, "overseas": true },
  { "name": "Sikandar Raza", "role": "all-rounder", "level": "pro", "score": 87, "overseas": true },
  { "name": "Shai Hope", "role": "wicket-keeper", "level": "pro", "score": 85, "overseas": true },
  { "name": "Chris Jordan", "role": "bowler", "level": "pro", "score": 84, "overseas": true },
  { "name": "Alzarri Joseph", "role": "bowler", "level": "pro", "score": 84, "overseas": true },
  { "name": "Jhye Richardson", "role": "bowler", "level": "pro", "score": 83, "overseas": true },
  { "name": "Tabraiz Shamsi", "role": "bowler", "level": "pro", "score": 83, "overseas": true },
  { "name": "Akeal Hosein", "role": "bowler", "level": "pro", "score": 82, "overseas": true },
  { "name": "Naveen Ul Haq", "role": "bowler", "level": "pro", "score": 82, "overseas": true }
];

const legendPlayers = [
  { "name": "Mitchell Starc", "role": "bowler", "level": "legend", "score": 95, "overseas": true },
  { "name": "KL Rahul", "role": "batter", "level": "legend", "score": 98, "overseas": false },
  { "name": "Suryakumar Yadav", "role": "batter", "level": "legend", "score": 98, "overseas": false },
  { "name": "Hardik Pandya", "role": "all-rounder", "level": "legend", "score": 97, "overseas": false },
  { "name": "Pat Cummins", "role": "all-rounder", "level": "legend", "score": 98, "overseas": true },
  { "name": "Shubman Gill", "role": "batter", "level": "legend", "score": 98, "overseas": false },
  { "name": "Rashid Khan", "role": "all-rounder", "level": "legend", "score": 97, "overseas": true },
  { "name": "Jos Buttler", "role": "wicket-keeper batter", "level": "legend", "score": 96, "overseas": true },
  { "name": "Sunil Narine", "role": "all-rounder", "level": "legend", "score": 95, "overseas": true },
  { "name": "Andre Russell", "role": "all-rounder", "level": "legend", "score": 94, "overseas": true },
  { "name": "Rishabh Pant", "role": "wicket-keeper batter", "level": "legend", "score": 95, "overseas": false },
  { "name": "Jofra Archer", "role": "bowler", "level": "legend", "score": 96, "overseas": true },
  { "name": "David Warner", "role": "batter", "level": "legend", "score": 97, "overseas": true },
  { "name": "Kane Williamson", "role": "batter", "level": "legend", "score": 95, "overseas": true },
  { "name": "Shakib Al Hasan", "role": "all-rounder", "level": "legend", "score": 95, "overseas": true }
];

const ultraLegendPlayers = [
  { "name": "Virat Kohli", "role": "batter", "level": "ultra-legend", "score": 100, "overseas": false },
  { "name": "MS Dhoni", "role": "wicket-keeper", "level": "ultra-legend", "score": 100, "overseas": false },
  { "name": "Rohit Sharma", "role": "batter", "level": "ultra-legend", "score": 99, "overseas": false },
  { "name": "Jasprit Bumrah", "role": "bowler", "level": "ultra-legend", "score": 99, "overseas": false }
];


const domesticPlayers = [
  { "name": "Ajay Mandal", "role": "all-rounder", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Manvanth Kumar", "role": "all-rounder", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Tripurana Vijay", "role": "all-rounder", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Madhav Tiwari", "role": "all-rounder", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Swastik Chikara", "role": "batter", "level": "domestic", "score": 78, "overseas": false },
  { "name": "Manoj Bhandage", "role": "all-rounder", "level": "domestic", "score": 78, "overseas": false },
  { "name": "Abhinandan Singh", "role": "bowler", "level": "domestic", "score": 78, "overseas": false },
  { "name": "Mohit Rathee", "role": "bowler", "level": "domestic", "score": 78, "overseas": false },
  { "name": "Shaik Rasheed", "role": "batter", "level": "domestic", "score": 75, "overseas": false },
  { "name": "Mukesh Choudhary", "role": "bowler", "level": "domestic", "score": 76, "overseas": false },
  { "name": "Kamlesh Nagarkoti", "role": "bowler", "level": "domestic", "score": 75, "overseas": false },
  { "name": "Ramakrishna Ghosh", "role": "all-rounder", "level": "domestic", "score": 75, "overseas": false },
  { "name": "Shreyas Gopal", "role": "bowler", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Andre Siddarth", "role": "batter", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Vansh Bedi", "role": "wicket-keeper", "level": "domestic", "score": 74, "overseas": false },
  { "name": "Atharva Taide", "role": "batter", "level": "domestic", "score": 80, "overseas": false },
  { "name": "Zeeshan Ansari", "role": "bowler", "level": "domestic", "score": 80, "overseas": false },
  { "name": "Umesh Yadav", "role": "bowler", "level": "domestic", "score": 79, "overseas": false },
  { "name": "Shardul Thakur", "role": "all-rounder", "level": "domestic", "score": 78, "overseas": false },
  { "name": "Shivam Mavi", "role": "bowler", "level": "domestic", "score": 77, "overseas": false },
  { "name": "Mayank Agarwal", "role": "batter", "level": "domestic", "score": 77, "overseas": false },
  { "name": "Prithvi Shaw", "role": "batter", "level": "domestic", "score": 76, "overseas": false },
  { "name": "K.S Bharat", "role": "wicket-keeper", "level": "domestic", "score": 75, "overseas": false }
];

const uncappedPlayers = [
  { "name": "Raj Angad Bawa", "role": "all-rounder", "level": "uncapped", "score": 75, "overseas": false },
  { "name": "Bevan Jacobs", "role": "batter", "level": "uncapped", "score": 72, "overseas": true },
  { "name": "Venkata P. Penmetsa", "role": "bowler", "level": "uncapped", "score": 72, "overseas": false },
  { "name": "Arjun Tendulkar", "role": "all-rounder", "level": "uncapped", "score": 76, "overseas": false },
  { "name": "Shrijith Krishnan", "role": "wicket-keeper batter", "level": "uncapped", "score": 70, "overseas": false },
  { "name": "Vignesh Puthur", "role": "bowler", "level": "uncapped", "score": 75, "overseas": false },
  { "name": "Ashwani Kumar", "role": "bowler", "level": "uncapped", "score": 82, "overseas": false },
  { "name": "Aniket Verma", "role": "batter", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Sachin Bedi", "role": "all-rounder", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Arshad Khan", "role": "all-rounder", "level": "uncapped", "score": 75, "overseas": false },
  { "name": "Gurnoor Singh Brar", "role": "bowler", "level": "uncapped", "score": 74, "overseas": false },
  { "name": "Karim Janat", "role": "all-rounder", "level": "uncapped", "score": 73, "overseas": true },
  { "name": "Kumar Kushagra", "role": "wicket-keeper", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Kulwant Khejroliya", "role": "bowler", "level": "uncapped", "score": 70, "overseas": false },
  { "name": "Manav Suthar", "role": "bowler", "level": "uncapped", "score": 68, "overseas": false },
  { "name": "Nishant Sindhu", "role": "bowler", "level": "uncapped", "score": 70, "overseas": false },
  { "name": "Luvnith Sisodia", "role": "wicket-keeper", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Manimaran Siddharth", "role": "bowler", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Shamar Joseph", "role": "bowler", "level": "uncapped", "score": 79, "overseas": true },
  { "name": "Arshin Kulkarni", "role": "all-rounder", "level": "uncapped", "score": 79, "overseas": false },
  { "name": "Prince Yadav", "role": "all-rounder", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Digvesh Singh Rathi", "role": "bowler", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Akash Singh", "role": "bowler", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Aryan Juyal", "role": "wicket-keeper", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Rajvardhan Hangargekar", "role": "bowler", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Himmat Singh", "role": "batter", "level": "uncapped", "score": 77, "overseas": false },
  { "name": "Yuvraj Chaudhary", "role": "all-rounder", "level": "uncapped", "score": 77, "overseas": false },
  { "name": "Vaibhav Suryavanshi", "role": "batter", "level": "uncapped", "score": 80, "overseas": false },
  { "name": "Akash Madhwal", "role": "bowler", "level": "uncapped", "score": 79, "overseas": false },
  { "name": "Shubham Dubey", "role": "batter", "level": "uncapped", "score": 79, "overseas": false },
  { "name": "Yudhvir Charak", "role": "bowler", "level": "uncapped", "score": 78, "overseas": false },
  { "name": "Dewald Brevis", "role": "batter", "level": "uncapped", "score": 73, "overseas": true },
  { "name": "Josh Little", "role": "bowler", "level": "uncapped", "score": 72, "overseas": true },
  { "name": "Finn Allen", "role": "batter", "level": "uncapped", "score": 72, "overseas": true },
  { "name": "Ben Duckett", "role": "batter", "level": "uncapped", "score": 71, "overseas": true }
];

module.exports = {
  elitePlayers,
  proPlayers,
  legendPlayers,
  ultraLegendPlayers,
  domesticPlayers,
  uncappedPlayers
};
